import type { Transaction } from "../../../shared/types/IndexTypes";

export const mockTransactions: Transaction[] = [
  // January 2025
  {
    id: "1",
    userId: "user1",
    amount: 5000,
    type: "income",
    categoryId: "salary",
    date: new Date("2026-01-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-01-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    userId: "user1",
    amount: -450,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-01-15"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    userId: "user1",
    amount: -200,
    type: "expense",
    categoryId: "utilities",
    date: new Date("2025-01-10"),
    description: "Electric Bill",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // February 2025
  {
    id: "5",
    userId: "user1",
    amount: 5200,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-02-05"),
    description: "Monthly Salary + Bonus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-02-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    userId: "user1",
    amount: -520,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-02-12"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    userId: "user1",
    amount: -180,
    type: "expense",
    categoryId: "utilities",
    date: new Date("2025-02-08"),
    description: "Water Bill",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // March 2025
  {
    id: "9",
    userId: "user1",
    amount: 5000,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-03-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    userId: "user1",
    amount: 500,
    type: "income",
    categoryId: "freelance",
    date: new Date("2025-03-15"),
    description: "Freelance Project",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "11",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-03-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12",
    userId: "user1",
    amount: -480,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-03-10"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // April 2025
  {
    id: "13",
    userId: "user1",
    amount: 5100,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-04-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "14",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-04-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "15",
    userId: "user1",
    amount: -600,
    type: "expense",
    categoryId: "transportation",
    date: new Date("2025-04-20"),
    description: "Car Repair",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "16",
    userId: "user1",
    amount: -300,
    type: "expense",
    categoryId: "entertainment",
    date: new Date("2025-04-14"),
    description: "Concert Tickets",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // May 2025
  {
    id: "17",
    userId: "user1",
    amount: 5000,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-05-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "18",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-05-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "19",
    userId: "user1",
    amount: -550,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-05-15"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "20",
    userId: "user1",
    amount: -220,
    type: "expense",
    categoryId: "utilities",
    date: new Date("2025-05-10"),
    description: "Internet Bill",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // June 2025
  {
    id: "21",
    userId: "user1",
    amount: 5300,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-06-05"),
    description: "Monthly Salary + Bonus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "22",
    userId: "user1",
    amount: 800,
    type: "income",
    categoryId: "freelance",
    date: new Date("2025-06-20"),
    description: "Freelance Project",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "23",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-06-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "24",
    userId: "user1",
    amount: -480,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-06-12"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "25",
    userId: "user1",
    amount: -400,
    type: "expense",
    categoryId: "entertainment",
    date: new Date("2025-06-18"),
    description: "Vacation",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // July 2025
  {
    id: "26",
    userId: "user1",
    amount: 5000,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-07-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "27",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-07-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "28",
    userId: "user1",
    amount: -520,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-07-15"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // August 2025
  {
    id: "29",
    userId: "user1",
    amount: 5200,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-08-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "30",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-08-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "31",
    userId: "user1",
    amount: -490,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-08-10"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "32",
    userId: "user1",
    amount: -250,
    type: "expense",
    categoryId: "utilities",
    date: new Date("2025-08-08"),
    description: "Electric Bill",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // September 2025
  {
    id: "33",
    userId: "user1",
    amount: 5000,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-09-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "34",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-09-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "35",
    userId: "user1",
    amount: -510,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-09-15"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // October 2025
  {
    id: "36",
    userId: "user1",
    amount: 5100,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-10-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "37",
    userId: "user1",
    amount: 600,
    type: "income",
    categoryId: "freelance",
    date: new Date("2025-10-12"),
    description: "Freelance Work",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "38",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-10-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "39",
    userId: "user1",
    amount: -530,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-10-20"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "40",
    userId: "user1",
    amount: -300,
    type: "expense",
    categoryId: "entertainment",
    date: new Date("2025-10-25"),
    description: "Birthday Party",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // November 2025
  {
    id: "41",
    userId: "user1",
    amount: 5000,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-11-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "42",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-11-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "43",
    userId: "user1",
    amount: -560,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-11-15"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "44",
    userId: "user1",
    amount: -200,
    type: "expense",
    categoryId: "utilities",
    date: new Date("2025-11-10"),
    description: "Gas Bill",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // December 2025
  {
    id: "45",
    userId: "user1",
    amount: 5500,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-12-05"),
    description: "Monthly Salary + Holiday Bonus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "46",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-12-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "47",
    userId: "user1",
    amount: -600,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-12-15"),
    description: "Holiday Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "48",
    userId: "user1",
    amount: -800,
    type: "expense",
    categoryId: "entertainment",
    date: new Date("2025-12-20"),
    description: "Christmas Gifts",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // January 2025
  {
    id: "49",
    userId: "user1",
    amount: 5000,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-01-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "50",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-01-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "51",
    userId: "user1",
    amount: -450,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-01-15"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // February 2025
  {
    id: "52",
    userId: "user1",
    amount: 5200,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-02-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "53",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-02-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "54",
    userId: "user1",
    amount: -480,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-02-12"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // March 2025
  {
    id: "55",
    userId: "user1",
    amount: 5000,
    type: "income",
    categoryId: "salary",
    date: new Date("2025-03-05"),
    description: "Monthly Salary",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "56",
    userId: "user1",
    amount: -1200,
    type: "expense",
    categoryId: "housing",
    date: new Date("2025-03-01"),
    description: "Rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "57",
    userId: "user1",
    amount: -500,
    type: "expense",
    categoryId: "food",
    date: new Date("2025-03-15"),
    description: "Groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];